name: circular_countdown_timer
description: Make an animated circular countdown using Circular Countdown Timer.
version: 1.0.0
homepage: https://github.com/MuhammadUsamaSiddiqui/circular_countdown_timer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: